### ISSUE TITLE
Array collection as argument

### ISSUE THREAD

**Issue by ivan-slepchenko** [DoclerLabs/hexMachina#74] opened 2016-09-05 11:46 UTC
Hi. I need to pass an Array as an argument. Can you please implement?
It should be something like this in xml:

``` xml
<collection id="windowList" type="Array#com.mvc.vo.window.IWindowVO">
        .
        .
        .
</collection>
```

**Comment by FrancisBourre** [comment] 2016-09-09 17:25
I think you mean to have instantiated Array with type parameter. Will work on it this week-end.

**Comment by Neverbirth** [comment] 2016-09-11 07:36
In case it was not clear: The problem is that Haxe generics are invariant, so `Array<Test>` cannot be assigned to `Array<ITest>`. Here the first will be inferred but we want the second.

**Comment by FrancisBourre** [comment] 2016-09-12 05:05
The feature is not available at this time, and when it will be, as you guess, it won't change haxe behavior... so I don't understand your comment @Neverbirth

**Comment by Neverbirth** [comment] 2016-09-12 05:59
I was just providing more info just in case. Right now users cannot have a parameter for a function/constructor of type `Array<ITest>`, because the framework will provide `Array<Test>` and Haxe won't allow for that. This can be a big problem when using a contract, we don't want to and a lot of times cannot set an specific implementation as a need, so hexMachina must be able to give us `Array<ITest>` (because it's obvious the framework won't change Haxe behavior for this).

**Comment by FrancisBourre** [comment] 2016-09-12 06:40
Ok, I got the point now. Thanks for your lights.

**Closed as completed** 2016-12-08 09:29 UTC
Labels: enhancement, priority moderate, hexIOC
