### ISSUE TITLE
Support for typed maps

### ISSUE THREAD

**Issue by st3veV** [DoclerLabs/hexMachina#142] opened 2016-10-24 06:58 UTC
Currently every HashMap defined in DSL is typed as `HashMap<Dynamic, Dynamic>`.
It'd be very useful to  be able to specify custom key and value types either as part of the type itself

``` xml
<collection id="fruits" type="hex.collection.HashMap<KeyType, ValueType>">
</collection>
```

or in more verbose way

``` xml
<collection id="fruits" type="hex.collection.HashMap" key-type="KeyType" value-type="ValueType">
</collection>
```

**Comment by Neverbirth** [comment] 2016-10-24 07:48
I'd say this is a duplicate of #74.

**Closed as completed** 2016-12-08 08:53 UTC
Labels: feature, priority moderate, hexInject, hexIOC
