### ISSUE TITLE
If there is an error in a MacroAdapterStrategy it shows wrong error

### ISSUE THREAD

**Issue by grosmar** [DoclerLabs/hexMachina#67] opened 2016-09-04 13:15 UTC
The compiler doesn't show the error of the original line, just refer to the XML where we define the AdapterStrategy.

It should point into the real class to the real line where the error happened.

**Comment by FrancisBourre** [comment] 2016-10-12 08:49
Could you add a functional test to reproduce the error please?

**Comment by FrancisBourre** [comment] 2016-11-11 08:33
If we cannot reproduce, I will close it for now.

**Closed as completed by FrancisBourre** 2016-11-11 08:33 UTC
Labels: bug
